#!/bin/bash
# Quick Deployment Commands for VPS
# Copy and paste these commands into your VPS terminal

echo "=========================================="
echo "MyArteLab VPS Deployment"
echo "=========================================="
echo ""
echo "Run these commands on your VPS:"
echo ""
echo "# 1. SSH to VPS"
echo "ssh root@72.61.97.210"
echo ""
echo "# 2. Navigate to project directory"
echo "cd /var/www/myartelab/backend"
echo ""
echo "# 3. Pull latest code"
echo "git pull origin main"
echo ""
echo "# 4. Install dependencies"
echo "npm install --production"
echo ""
echo "# 5. Create upload directories"
echo "mkdir -p /var/www/myartelab/backend/uploads/{avatars,covers,portfolio,services}"
echo "chown -R www-data:www-data /var/www/myartelab/backend/uploads"
echo "chmod -R 755 /var/www/myartelab/backend/uploads"
echo ""
echo "# 6. Restart PM2"
echo "pm2 restart myartelab"
echo ""
echo "# 7. Check status"
echo "pm2 logs myartelab --lines 50"
echo ""
echo "=========================================="
